### ISSUE TITLE
Support for lightline.vim

### ISSUE THREAD

**Issue by do-you-dare** [yasukotelin/shirotelin#12]
Hello!

Thanks for the nice colorscheme! It's always good to find more light colorschemes :)

I'm using [lightline.vim](https://github.com/itchyny/lightline.vim) statusline, and I'd like know if you could provide colors to use with it. Thanks!

**Comment by yasukotelin** [comment]
@dread-uo Thank you for using shirotelin😍!
I supports for lightline.vim now💪 Try use it🔥

**Comment by do-you-dare** [comment]
It is awesome! Works great :)

Thanks!
