### ISSUE TITLE
error in line 13

### ISSUE THREAD

**Issue by ghost** [yasukotelin/shirotelin#15]
init.vim
`syntax enable "включает подсветку синтаксиса
set termguicolors
set mouse+=a
set autoindent "авто-отступ строки
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set textwidth=80 "длина строки
filetype plugin indent on
"set number "показать номера строк

colorscheme shirotelin <-- 13 line

let g:airline_powerline_fonts=1 "Включить поддержку Powerline шрифтов
let g:Powerline_symbols='unicode' "Поддержка unicode

" Plagins
call plug#begin()

Plug 'yasukotelin/shirotelin'

Plug 'Pocco81/AutoSave.nvim'

Plug 'glepnir/galaxyline.nvim' , {'branch': 'main'}
Plug 'kyazdani42/nvim-web-devicons'
Plug 'romgrk/barbar.nvim'

Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'akinsho/flutter-tools.nvim'

Plug 'preservim/nerdtree'

Plug 'ryanoasis/vim-devicons'

call plug#end()

lua << EOF
  require("flutter-tools").setup{}
EOF

lua << EOF
  require("telescope").load_extension("flutter")
EOF

lua << EOF
  require('spaceline')
EOF`

**Comment by ghost** [comment]
and the default novim theme is loaded, but if I write in vim itself :colorscheme shirotelin, it will be applied
sorry i am noob

**Comment by yasukotelin** [comment]
@MitaiGit 
I think... you need to write `colorscheme shirotelin` below `call plug#end()`.

```vim
" Plagins
call plug#begin()

Plug 'yasukotelin/shirotelin'

Plug 'Pocco81/AutoSave.nvim'

Plug 'glepnir/galaxyline.nvim' , {'branch': 'main'}
Plug 'kyazdani42/nvim-web-devicons'
Plug 'romgrk/barbar.nvim'

Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'akinsho/flutter-tools.nvim'

Plug 'preservim/nerdtree'

Plug 'ryanoasis/vim-devicons'

call plug#end()

colorscheme shirotelin
```

🤗

**Comment by ghost** [comment]
thanks, sorry i am noob))
dark theme?
