### ISSUE TITLE
port to kakoune editor

### ISSUE THREAD

**Issue by ghost** [yasukotelin/shirotelin#7]
I am a huge fan of shirotelin color scheme!  I wanted to let you know that I have ported it to kakoune https://github.com/coder5506/shirotelin-kakoune

I'm happy to maintain it, or you could take it over if you prefer to keep it with the other ports.

**Comment by yasukotelin** [comment]
@coder5506 
I'm so happy for your pull request and your good port project!!

I want you to keep maintaining it😍 
Do you mind if I introduce your project in my [README](https://github.com/yasukotelin/shirotelin/commit/ef7459eba485acf5ffcbb798d7b8c3ac9189d02f)?

**Comment by ghost** [comment]
Great!  I'll be happy to continue to work on it.  And of course I don't mind if you link to it.  Thanks!
